services:
  - type: web
    name: mcbe-tiers-app
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm start
    healthCheckPath: /api/players
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: mcbe-tiers-db
          property: connectionString

databases:
  - name: mcbe-tiers-db
    plan: free
    region: oregon